spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/nekst
        username: postgres
    jpa:
        database: Postgresql
    flyway:
        schemas: nekst


