version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test

    steps:
      - checkout

      # run tests!
      - run:
            name: build
            command: |
              wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
              unzip sonar-scanner-cli-3.2.0.1227-linux.zip
              gradle test jacocoTestReport --info
              export SONAR_SCANNER_OPTS="-Xmx2048m"
              eval ./sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner   -Dsonar.projectKey=Weiller_nekst-servico \
                                                                        -Dsonar.organization=weiller-github \
                                                                        -Dsonar.sources=src/main/kotlin \
                                                                        -Dsonar.coverage.jacoco.xmlReportPaths=build/jacocoXml.xml \
                                                                        -Dsonar.host.url=https://sonarcloud.io \
                                                                        -Dsonar.binaries=build/classes \
                                                                        -Dsonar.login=a8a4aa2b2a04425660ba4e0311baeacddb3eda64


      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz

            sudo mv /tmp/docker/* /usr/bin

      - run:
          name: Build Docker image
          command: docker build ./ -t springbootapp