version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # run tests!
      - run: gradle build -x test

      - run:
          name: Build Docker image
          command: docker build ./ -t springbootapp