version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # run tests!
      #- run: gradle build -x test

      - run:
          name: Install docker
          command: |
            apt-get install -y apt-transport-https ca-certificates software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

            apt-get install -y docker-ce
            docker --version

      - run:
          name: Build Docker image
          command: docker build ./ -t springbootapp